### ISSUE TITLE
在observer.js中注释的修改

### ISSUE THREAD

**Issue by maiff** [youngwind/bue#3]
在这个文件中第26行，
` // TODO 这里enumerable一定要为false,否则会触发死循环, 原因未明
    // 将当前对象存储到当前对象的$observer属性中`
因为这里如果不设置不可枚举，之后的walk会遍历$observer，导致死循环。
还有顺带提一嘴，好多代码跟vue1.0一模一样。
为什么js的模块化混着用？

**Comment by youngwind** [comment]
1. 关于死循环的原因解释，你说得对。
2. 本来此项目便是对 vue 早期代码的模仿（希望通过模仿来理解其原理），所以有很多一样也就不足为奇。
3. 什么叫“js的模块化混着用？”

@maiff

**Comment by maiff** [comment]
@youngwind 
当然像你那么用当然是没问题的，但import是es6的规范，exports是commonjs的规范。当然import和export，是最好的，因为打包的时候可以按需打包。

**Comment by youngwind** [comment]
原来你说的是这个问题。嗯，当初写的时候确实没有注意到这个。 @maiff
